import type { Metadata } from 'next';
import { Outfit, Volkhov } from 'next/font/google';
import './globals.css';

const font = Outfit({ subsets: ['latin'] });
const volkhov = Volkhov({ subsets: ['latin'], weight: ['400', '700'] });

export const metadata: Metadata = {
  title: 'Umutsakura',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={[font.className, volkhov.className].toString()}>
        {children}
      </body>
    </html>
  );
}
